/**
 * Application configuration.
 *
 * Resolution order:
 *   1. js/env.js            (git-ignored; generated by the deploy workflow)
 *   2. localStorage 'wih.env' (handy for local experiments)
 *
 * If neither provides a Supabase URL the app shows a setup screen instead
 * of failing silently.
 */

const DEFAULTS = {
  supabaseUrl: '',
  supabaseAnonKey: '',
  vapidPublicKey: ''
};

let fileEnv = {};
try {
  const mod = await import('./env.js');
  fileEnv = mod.ENV || mod.default || {};
} catch {
  // env.js has not been created yet — handled by isConfigured() below.
}

let localEnv = {};
try {
  localEnv = JSON.parse(localStorage.getItem('wih.env') || '{}');
} catch {
  localEnv = {};
}

export const CONFIG = Object.freeze({
  ...DEFAULTS,
  ...fileEnv,
  ...localEnv,

  /** Everything is displayed in the organisation's timezone. */
  timezone: 'Asia/Beirut',
  locale: 'en-GB',

  /** Fallback duration buttons; overridden by the `quick_durations` setting. */
  quickDurations: [5, 10, 15, 20, 30, 45, 60, 120],

  /** How long a finished status stays on screen as "expired" before nagging. */
  staleAfterMinutes: 15
});

/** True when we have enough to talk to Supabase at all. */
export function isConfigured() {
  return Boolean(
    CONFIG.supabaseUrl &&
    CONFIG.supabaseAnonKey &&
    !CONFIG.supabaseUrl.includes('YOUR-PROJECT-REF') &&
    !CONFIG.supabaseAnonKey.includes('YOUR-ANON')
  );
}

/** Human readable labels for every status the system understands. */
export const STATUS_META = Object.freeze({
  available: { label: 'Available',  short: 'Available',  icon: '🟢', tone: 'ok',      hint: 'Free to help' },
  busy:      { label: 'Busy',       short: 'Busy',       icon: '🟡', tone: 'warn',    hint: 'Working on a task' },
  serving:   { label: 'With someone', short: 'Serving',  icon: '🔵', tone: 'info',    hint: 'Currently helping a colleague' },
  traveling: { label: 'On the way',  short: 'Traveling', icon: '🚶', tone: 'info',    hint: 'Walking to another building' },
  break:     { label: 'On break',    short: 'Break',     icon: '☕', tone: 'muted',   hint: 'Back shortly' },
  meeting:   { label: 'In a meeting', short: 'Meeting',  icon: '📋', tone: 'warn',    hint: 'In a meeting' },
  offsite:   { label: 'Off site',    short: 'Off site',  icon: '🚗', tone: 'muted',   hint: 'Away from the campus' },
  done:      { label: 'Finished for the day', short: 'Finished', icon: '🌙', tone: 'muted', hint: 'Back tomorrow' }
});

export const PRIORITY_META = Object.freeze({
  normal:      { label: 'Normal',      icon: '🟡', rank: 2, tone: 'warn' },
  urgent:      { label: 'Urgent',      icon: '🟠', rank: 1, tone: 'urgent' },
  very_urgent: { label: 'Very urgent', icon: '🔴', rank: 0, tone: 'danger' }
});

export const REQUEST_STATUS_META = Object.freeze({
  pending:     { label: 'Pending',     icon: '⏳', tone: 'muted' },
  accepted:    { label: 'Accepted',    icon: '👍', tone: 'info' },
  in_progress: { label: 'In progress', icon: '🔧', tone: 'warn' },
  completed:   { label: 'Completed',   icon: '✅', tone: 'ok' },
  rejected:    { label: 'Rejected',    icon: '⛔', tone: 'danger' },
  cancelled:   { label: 'Cancelled',   icon: '✖️', tone: 'muted' }
});
