/**
 * Application configuration.
 *
 * Resolution order:
 *   1. js/env.js            (git-ignored; generated by the deploy workflow)
 *   2. localStorage 'wih.env' (handy for local experiments)
 *
 * If neither provides a Supabase URL the app shows a setup screen instead
 * of failing silently.
 */

import { t } from './i18n.js';

const DEFAULTS = {
  supabaseUrl: '',
  supabaseAnonKey: '',
  vapidPublicKey: ''
};

let fileEnv = {};
try {
  const mod = await import('./env.js');
  fileEnv = mod.ENV || mod.default || {};
} catch {
  // env.js has not been created yet — handled by isConfigured() below.
}

let localEnv = {};
try {
  localEnv = JSON.parse(localStorage.getItem('wih.env') || '{}');
} catch {
  localEnv = {};
}

export const CONFIG = Object.freeze({
  ...DEFAULTS,
  ...fileEnv,
  ...localEnv,

  /** Everything is displayed in the organisation's timezone. */
  timezone: 'Asia/Beirut',
  locale: 'en-GB',

  /** Fallback duration buttons; overridden by the `quick_durations` setting. */
  quickDurations: [5, 10, 15, 20, 30, 45, 60, 120],

  /** How long a finished status stays on screen as "expired" before nagging. */
  staleAfterMinutes: 15
});

/** True when we have enough to talk to Supabase at all. */
export function isConfigured() {
  return Boolean(
    CONFIG.supabaseUrl &&
    CONFIG.supabaseAnonKey &&
    !CONFIG.supabaseUrl.includes('YOUR-PROJECT-REF') &&
    !CONFIG.supabaseAnonKey.includes('YOUR-ANON')
  );
}

/** Human readable labels for every status the system understands. */
/**
 * Icon and colour tone are language-independent and live here. `label`
 * and `hint` are getters that read from i18n, so every existing
 * `meta.label` call site translates itself when the language changes.
 */
export const STATUS_META = Object.freeze(Object.fromEntries(
  [
    ['available', '🟢', 'ok'],
    ['busy',      '🟡', 'warn'],
    ['serving',   '🔵', 'info'],
    ['traveling', '🚶', 'info'],
    ['break',     '☕', 'muted'],
    ['meeting',   '📋', 'warn'],
    ['offsite',   '🚗', 'muted'],
    ['done',      '🌙', 'muted']
  ].map(([key, icon, tone]) => [key, Object.freeze({
    icon, tone,
    get label() { return t(`status.${key}`); },
    get short() { return t(`status.${key}`); },
    get hint()  { return t(`status.${key}.hint`); }
  })])
));

/*
 * Four levels, ranked 0 (drop everything) to 3 (whenever you can).
 *
 * The fourth exists because three stopped discriminating: once "very
 * urgent" was the top of the scale, everything that actually stopped
 * work got filed there and the genuine emergencies were buried among
 * the merely annoying ones. `life_death` gives the top somewhere to go
 * and leaves "very urgent" meaning what it says.
 */
export const PRIORITY_META = Object.freeze(Object.fromEntries(
  [
    ['normal',      '🟡', 3, 'warn'],
    ['urgent',      '🟠', 2, 'urgent'],
    ['very_urgent', '🔴', 1, 'danger'],
    ['life_death',  '🚨', 0, 'critical']
  ].map(([key, icon, rank, tone]) => [key, Object.freeze({
    icon, rank, tone,
    get label() { return t(`priority.${key}`); }
  })])
));

/*
 * One colour per state, and never the same colour twice. A request walks
 * RECEIVED (blue, it has been seen) -> ACCEPTED (yellow, he has taken it
 * on) -> IN PROGRESS (amber, he is at it) -> DONE (green). On hold is
 * orange because it is the one state that needs chasing, and refused is
 * red. The badge always prints its own words, so none of this depends on
 * the reader seeing colour at all.
 */
export const REQUEST_STATUS_META = Object.freeze(Object.fromEntries(
  [
    ['pending',     '⏳', 'info'],
    ['accepted',    '👍', 'accent'],
    ['in_progress', '🔧', 'warn'],
    ['paused',      '⏸️', 'urgent'],
    ['completed',   '✅', 'ok'],
    ['rejected',    '⛔', 'danger'],
    ['cancelled',   '✖️', 'muted']
  ].map(([key, icon, tone]) => [key, Object.freeze({
    icon, tone,
    get label() { return t(`reqstatus.${key}`); }
  })])
));

/* ------------------------------------------------------------------ */
/* Display helpers                                                     */
/*                                                                     */
/* The META objects above keep the icon and the colour tone, which do   */
/* not change between languages. Every visible label goes through i18n. */
/* ------------------------------------------------------------------ */

export const CHANNELS = Object.freeze(Object.fromEntries(
  [
    ['app',       '📱'],
    ['whatsapp',  '💬'],
    ['phone',     '📞'],
    ['in_person', '🚶'],
    ['other',     '📝']
  ].map(([key, icon]) => [key, Object.freeze({
    icon,
    get label() { return t(`channel.${key}`); }
  })])
));

export const CHANNEL_KEYS = Object.freeze(['app', 'whatsapp', 'phone', 'in_person', 'other']);
